spring.application.name=Examen3AccesoDatos


spring.mongodb.uri=mongodb+srv://pabloglt95:root@cluster0.qbuwpow.mongodb.net/store?appName=Cluster0
spring.mongodb.database=store

#Swagger pase del json al formato navegador
springdoc.swagger-ui.path=/


item.stockMinimo=100